Refactoring of home
YorkIsMine/ExpenseApp pull request #5
Opened 2019-11-13 16:35 UTC by YorkIsMine

2019-11-13 18:54 UTC, Shiplayer requested changes

2019-11-13 18:54 UTC, Shiplayer commented on app/src/main/java/com/yorkismine/expenseapp/ui/home/HomeViewModel.java
> +                              Fragment fragment, final ExpenseAdapter adapter,
Убрать фрагмент UI элементы с viewmodel.

2019-11-13 18:54 UTC, Shiplayer commented on app/src/main/java/com/yorkismine/expenseapp/ui/home/HomeViewModel.java
> +                btnBySum.setOnClickListener(new View.OnClickListener() {
сделать методы, которые будут вызываться из ui при нажатии на кнопку и отправлять событие во viewmodel

2019-11-13 18:54 UTC, Shiplayer commented on app/src/main/java/com/yorkismine/expenseapp/ui/home/HomeViewModel.java
> +    public void setupLogicOfSwipe(final ExpenseViewModel expenseViewModel, final Context context, final ExpenseAdapter adapter, RecyclerView recyclerView){
пока что вернуть этот метод обратно в ui

2019-11-13 18:54 UTC, Shiplayer commented on app/src/main/java/com/yorkismine/expenseapp/ui/home/HomeViewModel.java
> +    public ArrayAdapter<String> getGridAdapter(View root, String[] data){
этот тоже в ui

2019-11-13 18:54 UTC, Shiplayer commented on app/src/main/java/com/yorkismine/expenseapp/ui/home/HomeViewModel.java
> +    private List<Expense> sortByDate(List<Expense> byDate) {
Логика сортировки не должна быть в ui. Исправить ее для даты и суммы, тем более, если дата и сумма являются строками.

2019-11-15 14:24 UTC, Shiplayer commented on app/src/main/java/com/yorkismine/expenseapp/model/ExpenseKotl.kt
> +class ExpenseKotl(){
https://medium.com/mindorks/room-kotlin-android-architecture-components-71cad5a1bb35
Посмотри вот эту статью.
Лучше сделать его как data class

2019-11-15 14:24 UTC, Shiplayer commented on app/src/main/java/com/yorkismine/expenseapp/model/ExpenseRepositoryKotl.kt
> +    fun sortByDate(): LiveData<List<ExpenseKotl>> {
Все три сортировки я бы убрал, нам больше интересней отсортировать их программно

2019-11-15 14:24 UTC, Shiplayer commented on app/src/main/java/com/yorkismine/expenseapp/model/ExpenseViewModelKotl.kt
> +    private val sortBySum: LiveData<List<ExpenseKotl>>
Убрать все три поля, sortByDate, sortByName и sortBySum.
Сделать поле sortType.
Добавить метод для отправки типа сортировки в sortType, если пользователь выбрал по какому параметру сортировать.

2019-11-15 14:24 UTC, Shiplayer commented on app/src/main/java/com/yorkismine/expenseapp/model/ExpenseViewModelKotl.kt
> +        allExpenses = repository.allExpenses
allExpenses должен получить уже полностью отсортированный список. 
При изменении в sortType необходимо изменить порядок элементов в repository.allExpenses или отобрать элементы подходящие под условия.

2019-11-15 14:24 UTC, Shiplayer commented on app/src/main/java/com/yorkismine/expenseapp/model/ExpenseRepositoryKotl.kt
> +    private class InsertExpenseAsyncTask(private val expenseDAO: ExpenseDAOKotl) : AsyncTask<ExpenseKotl, Void, Void>() {
Было бы классно, все эти AsyncTask обобщить, но не обязательно

2019-11-15 14:24 UTC, Shiplayer commented on app/build.gradle
> +    compile "androidx.core:core-ktx:+"
implementation

2019-11-18 06:52 UTC, Shiplayer requested changes

2019-11-18 06:52 UTC, Shiplayer commented on app/src/main/java/com/yorkismine/expenseapp/model/ExpenseKotl.kt
> +data class ExpenseKotl(
У данного класса свойства не могут быть приватными, иначе мы не сможем получить данные. Kotlin автоматически генерирует геттеры и сетторы для этих полей, если ты устанавливаешь их как private, то эти геттеры и сетторы тоже будут доступны только внутри данного класса

2019-11-18 06:52 UTC, Shiplayer commented on app/src/main/java/com/yorkismine/expenseapp/ui/statistics/StatisticsFragmentKotl.kt
> +class StatisticsFragmentKotl : Fragment() {
Зачем этот класс надо было менять в данном пулл реквесте?

2019-11-18 06:52 UTC, Shiplayer commented on app/src/main/java/com/yorkismine/expenseapp/ui/statistics/StatisticsViewModelKotl.kt
> +class StatisticsViewModelKotl(application: Application) : AndroidViewModel(application) {
Аналогично, зачем в этом реквесте?

2019-11-18 06:52 UTC, Shiplayer commented on app/src/main/java/com/yorkismine/expenseapp/ui/statistics/StatisticsViewModelKotl.kt
> +class StatisticsViewModelKotl(application: Application) : AndroidViewModel(application) {
почему создаешь копии с суффиксом Kotl? Почему сразу оригинальный не меняешь? (PS это не надо делать в этом пулл реквесте)

2019-11-19 17:12 UTC, YorkIsMine commented on app/src/main/java/com/yorkismine/expenseapp/ui/statistics/StatisticsFragmentKotl.kt
> +class StatisticsFragmentKotl : Fragment() {
то есть?

2019-11-19 17:14 UTC, YorkIsMine commented on app/src/main/java/com/yorkismine/expenseapp/ui/statistics/StatisticsViewModelKotl.kt
> +class StatisticsViewModelKotl(application: Application) : AndroidViewModel(application) {
а когда надо?

2019-11-19 17:23 UTC, YorkIsMine commented on app/src/main/java/com/yorkismine/expenseapp/model/ExpenseRepositoryKotl.kt
> +    private class InsertExpenseAsyncTask(private val expenseDAO: ExpenseDAOKotl) : AsyncTask<ExpenseKotl, Void, Void>() {
А каким образом обобщить-то? Сделав абстрактный класс? Но у классов есть конструктор, где передается DAO. По сути ничего вообще не изменится, кроме увеличения кода

2019-11-19 18:32 UTC, Shiplayer commented on app/src/main/java/com/yorkismine/expenseapp/ui/statistics/StatisticsViewModelKotl.kt
> +class StatisticsViewModelKotl(application: Application) : AndroidViewModel(application) {
Refactoring of home не планировалось изменять код для Statistics

2019-11-20 07:32 UTC, Shiplayer commented on app/src/main/java/com/yorkismine/expenseapp/model/ExpenseRepositoryKotl.kt
> +    private class InsertExpenseAsyncTask(private val expenseDAO: ExpenseDAOKotl) : AsyncTask<ExpenseKotl, Void, Void>() {
Предлагалось сделать тот же самый класс, только class ActionExpenseAsyncTask(private val action: (Expense) -> Unit))
Где action лямбда функция, которая может выполнить любое выражение внутри своего потока

2019-11-20 08:26 UTC, Shiplayer requested changes

2019-11-20 08:26 UTC, Shiplayer commented on app/src/main/java/com/yorkismine/expenseapp/model/ExpenseViewModel.java
> +            case 0:
Вместо численных значений, ввести константы

2019-11-20 08:26 UTC, Shiplayer commented on app/src/main/java/com/yorkismine/expenseapp/ui/home/HomeFragment.java
>                          for (int i = 0; i < expenses.size(); i++) {
Все что находится в блоке for вынести в метод onItemSelected

2019-11-20 08:26 UTC, Shiplayer commented on app/src/main/java/com/yorkismine/expenseapp/ui/home/HomeFragment.java
>                  expenseViewModel.getAllExpenses().observe(HomeFragment.this, new Observer<List<Expense>>() {
получение элементов из viewmodel должна происходить вне установки листнера для спинера. Для примера, перед 109 сточкой.

2019-11-20 08:26 UTC, Shiplayer commented on app/src/main/java/com/yorkismine/expenseapp/ui/home/HomeFragment.java
>                              switch (currentDate) {
закоммитить данный `switch`. Будет отдельная задача на его исправление

2019-11-20 08:26 UTC, Shiplayer commented on app/src/main/java/com/yorkismine/expenseapp/ui/home/HomeFragment.java
>                          // Add sorting by request
убрать комментарий

2019-11-20 08:26 UTC, Shiplayer commented on app/src/main/java/com/yorkismine/expenseapp/ui/home/HomeFragment.java
>      private List<Expense> sortByName(List<Expense> byDate) {
Убрать данные методы сортировок

2019-11-20 08:26 UTC, Shiplayer commented on app/src/main/java/com/yorkismine/expenseapp/ui/home/HomeFragment.java
>      public void onActivityResult(int requestCode, int resultCode, Intent data) {
убрать метод

2019-11-20 08:26 UTC, Shiplayer commented on app/src/main/java/com/yorkismine/expenseapp/model/ExpenseViewModel.java
> +//Он уже ж не нужен
убрать комментарий

2019-11-20 08:26 UTC, Shiplayer commented on app/src/main/java/com/yorkismine/expenseapp/ui/home/HomeViewModel.java
> +    public ArrayAdapter<String> getGridAdapter(View root, String[] data){
убрать от сюда, если это уже в UI

2019-11-20 08:26 UTC, Shiplayer commented on app/src/main/java/com/yorkismine/expenseapp/ui/home/HomeViewModel.java
> +    private List<Expense> sortByDate(List<Expense> byDate) {
убрать от сюда, если это уже в UI

2019-11-20 08:29 UTC, Shiplayer requested changes

2019-11-20 08:29 UTC, Shiplayer commented on app/src/main/java/com/yorkismine/expenseapp/model/ExpenseApplication.java
> +package com.yorkismine.expenseapp.model;
Application класс не должен быть в папке model, перенести его в пакет `com.yorkismine.expenseapp`

2019-11-22 09:06 UTC, Shiplayer requested changes

2019-11-22 09:06 UTC, Shiplayer commented on app/src/main/java/com/yorkismine/expenseapp/model/ExpenseViewModel.java
>      private Comparator<Expense> getComparatorByType(int type) {
Вынести данный метод в FilterUtils

2019-11-22 09:06 UTC, Shiplayer commented on app/src/main/java/com/yorkismine/expenseapp/model/ExpenseViewModel.java
> +    public final static int SHOW_BY_YEAR = 128;
Константы тоже в FilterUtils

2019-11-22 09:06 UTC, Shiplayer commented on app/src/main/java/com/yorkismine/expenseapp/utils/Constants.java
> +    public static final int TYPE_SUM = 2;
Убрать данные константы из этого файла

2019-11-22 09:06 UTC, Shiplayer commented on app/src/main/java/com/yorkismine/expenseapp/ui/home/HomeFragment.java
> +                expenseViewModel.sort(TYPE_DATE);
Заменить данные константы на новые

2019-11-22 09:06 UTC, Shiplayer commented on app/src/main/java/com/yorkismine/expenseapp/model/ExpenseViewModel.java
>      private MutableLiveData<Integer> mutableLiveData = new MutableLiveData<>();
переименовать в sortLiveData

2019-11-25 19:27 UTC, Shiplayer requested changes

2019-11-25 19:27 UTC, Shiplayer commented on app/src/main/java/com/yorkismine/expenseapp/model/FilterUtils.kt
> +            SORT_BY_NAME -> Comparator<Expense>{p0, p1 -> (p0!!.title)!!.compareTo(p1!!.title!!)}
Code style

2019-11-27 06:35 UTC, Shiplayer approved these changes

2019-11-30 17:15 UTC, merged